server:
  port: 9002

spring:
  application:
    name: user-service
  data:
    mongodb:
      authentication-database: bw4akzgkumz3gdj
      username: u4nbdinxuhjwlb1sfraa
      password: iZxFAGAwsZGuVJlovyBI
      database: bw4akzgkumz3gdj
      port: 27017
      host: bw4akzgkumz3gdj-mongodb.services.clever-cloud.com