server:
  port: 9002

spring:
  application:
    name: user-service
  data:
    mongodb:
      user: u4nbdinxuhjwlb1sfraa
      password: iZxFAGAwsZGuVJlovyBI
      uri: mongodb://bw4akzgkumz3gdj-mongodb.services.clever-cloud.com:27017/bw4akzgkumz3gdj


jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 86400