server:
  port: 9003

spring:
  application:
    name: ext-com-service

sftp:
  server_host: localhost
  server_port: 3333
  server_username: test
  server_password: password
  client_host: localhost
  client_port: 3333
  client_username: test
  client_password: password